name: Build application code

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build]
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'edtan/sandbox'
          ref: 'refs/heads/master'

      - name: "Run code"
        run: python app-code/main.py
