name: Build application code

on:
  repository_dispatch:
    types: [build]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "cwi_workflow_id=${{ github.event.client_payload.cwi_workflow_id }}"
        run: |
          echo "${{ toJson(github.event.client_payload) }}"

      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repository_name }}
          ref: ${{ github.event.client_payload.commit_sha }}

      - name: Set version
        id: set-version
        working-directory: ${{ github.event.client_payload.repository_subdirectory }}
        run: |
          echo "::set-output name=version::$(cat version)"

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: edtan/sandbox-cicd/sandbox
          tags: ${{ github.event.client_payload.branch }}-${{ steps.set-version.outputs.version }}
          path: ${{ github.event.client_payload.repository_subdirectory }}

      - name: "workflow_output|build_artifact_version=${{ steps.set-version.outputs.version }}|build_artifact_url=docker.pkg.github.com/edtan/sandbox-cicd/sandbox:${{ github.event.client_payload.branch }}-${{ steps.set-version.outputs.version }}"
        run: |
          echo ''