name: Build application code

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build]
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print repository_dispatch payload
        run: |
          print ${{ toJson(github.event.client_payload) }}
          
      - uses: actions/checkout@v2
        with:
          repository: 'edtan/sandbox'
          # TODO: fix ref so that it also works with workflow_dispatch
          ref: ${{ github.event.client_payload.branch }}

      - name: "Run code"
        run: python app-code/main.py
