name: Build application code

on:
  repository_dispatch:
    types: [build]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print repository_dispatch payload
        run: |
          echo "${{ toJson(github.event.client_payload) }}"

      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repository_full_name }}
          ref: ${{ github.event.client_payload.head_commit_sha }}

      - name: Set version ${{ steps.set-version.outputs.version }}
        id: set-version
        working-directory: app-code
        run: |
          echo "test"

      - name: Dynamic name test 
        run: |
          echo "${{ toJson(github.event.client_payload) }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: edtan/sandbox-cicd/sandbox
          tags: ${{ github.event.client_payload.branch }}-${{ steps.set-version.outputs.version }}
          path: app-code
